#!/bin/bash

# ssh disable password authentication
sed -i 's/^PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
systemctl restart sshd.service

# Time zone
/bin/cp -p /usr/share/zoneinfo/Japan /etc/localtime
echo 'ZONE="Asia/Tokyo"' > /etc/sysconfig/clock
echo 'UTC=false' >> /etc/sysconfig/clock

# Yum
## Utility
yum install -y \
    bash-completion \
    bind-utils \
    lsof \
    net-tools \
    screen \
    sos \
    sysstat

## Editor
yum install -y \
    vim-enhanced

## MariaDB
yum install -y mariadb mariadb-server mariadb-devel

## DevTools
yum -y groupinstall "Development Tools"

## for Redmine
yum -y install openssl-devel readline-devel zlib-devel curl-devel libyaml-devel libffi-devel
yum -y install ImageMagick ImageMagick-devel ipa-pgothic-fonts
yum -y install ruby ruby-devel rubygems rubygem-bundler


## mariadb settings
mv /etc/my.cnf /tmp/my.cnf
curl -OL https://raw.githubusercontent.com/kazuhisya/SL-Redmine/master/conf/mariadb-my.cnf
mv mariadb-my.cnf /etc/my.cnf

## Service Enable and Start
systemctl enable mariadb.service
systemctl start mariadb.service

## create mariadb password
PASS=`date +%s | sha256sum | base64 | head -c 32`
echo $PASS > /root/db_password.txt

## Create WordPress DB
/usr/bin/mysql -e "CREATE DATABASE redmine DEFAULT CHARACTER SET utf8;" -D mysql
/usr/bin/mysql -e "GRANT ALL PRIVILEGES ON redmine.* TO redmine@'%' IDENTIFIED BY '${PASS}';" -D mysql

## mysql_secure_installation
/usr/bin/mysqladmin drop test -f
/usr/bin/mysql -e "DELETE FROM mysql.user WHERE User = '';" -D mysql
/usr/bin/mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');" -D mysql
/usr/bin/mysql -e "SET PASSWORD FOR 'root'@'::1' = PASSWORD('${PASS}');" -D mysql
/usr/bin/mysql -e "SET PASSWORD FOR 'root'@'127.0.0.1' = PASSWORD('${PASS}');" -D mysql
/usr/bin/mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${PASS}');" -D mysql
/usr/bin/mysqladmin flush-privileges -p${PASS}

## Ruby Gems
echo "gem: --no-ri --no-rdoc --user-install" > /root/.gemrc
echo "export PATH=\"\$HOME/.gem/ruby/bin:\$PATH\"" >> /root/.bashrc
source /root/.bashrc
gem install bundler

## Redmine Download
curl -OL http://www.redmine.org/releases/redmine-3.0.1.tar.gz
tar xvf redmine-3.0.1.tar.gz
mv redmine-3.0.1 /var/lib/redmine

## Redmine Settings
cat << EOF | tee /var/lib/redmine/config/database.yml > /dev/null
production:
  adapter: mysql2
  database: redmine
  host: localhost
  username: root
  password: "$PASS"
  encoding: utf8
EOF

cp /var/lib/redmine/config/configuration.yml.example /var/lib/redmine/config/configuration.yml
sed -i -e 's/  rmagick_font_path:/  rmagick_font_path: \/usr\/share\/fonts\/ipa-pgothic\/ipagp.ttf/' /var/lib/redmine/config/configuration.yml

## Redmine Install
echo "gem \"unicorn\"" > Gemfile.local
bundle install --without development test --path vendor/bundle
bundle exec rake generate_secret_token
RAILS_ENV=production bundle exec rake db:migrate
RAILS_ENV=production REDMINE_LANG=ja bundle exec rake redmine:load_default_data

## Unicorn
cat << EOF | tee config/unicorn.rb > /dev/null
working_directory "/var/lib/redmine"
pid "/var/lib/redmine/tmp/pids/unicorn.pid"
stderr_path "/var/lib/redmine/log/unicorn.log"
stdout_path "/var/lib/redmine/log/unicorn.log"

listen "tmp/sockets/unicorn.sock"
worker_processes 2
timeout 30
EOF

cat << EOF | tee /usr/lib/systemd/system/redmine-unicorn.service > /dev/null
[Unit]
Description=Redmine Unicorn Server

[Service]
WorkingDirectory=/var/lib/redmine
Environment=RAILS_ENV=production
SyslogIdentifier=redmine-unicorn
PIDFile=/var/lib/redmine/tmp/pids/unicorn.pid

ExecStart=/root/.gem/ruby/bin/bundle exec "unicorn_rails -c config/unicorn.rb -E production"
ExecStop=/usr/bin/kill -QUIT $MAINPID
ExecReload=/bin/kill -USR2 $MAINPID

[Install]
WantedBy=multi-user.target
EOF

systemctl enable redmine-unicorn.service
systemctl start redmine-unicorn.service

## Nginx Repository
cat << EOF | tee /etc/yum.repos.d/nginx-mainline.repo > /dev/null
[nginx-mainline]
name=nginx mainline repo
baseurl=http://nginx.org/packages/mainline/centos/7/x86_64/
gpgcheck=0
enabled=1
EOF

## Hack for Nginx
echo 'net.ipv4.tcp_tw_recycle = 1' >> /etc/sysctl.conf
echo 'net.ipv4.tcp_tw_reuse = 1' >> /etc/sysctl.conf
echo 'net.ipv4.tcp_max_syn_backlog = 100000' >> /etc/sysctl.conf
echo 'net.netfilter.nf_conntrack_max = 100000' >> /etc/sysctl.conf
echo 'net.nf_conntrack_max = 100000' >> /etc/sysctl.conf
echo 'fs.file-max = 320000' >> /etc/sysctl.conf
sysctl -p

## Install Nginx and AB tools
yum install -y nginx

curl -OL https://raw.githubusercontent.com/kazuhisya/SL-Redmine/master/conf/nginx-redmine.conf
mv nginx-redmine.conf /etc/nginx/conf.d/redmine.conf
systemctl enable nginx.service
systemctl start nginx.service
